### ISSUE TITLE
About your programmer ~~

### ISSUE THREAD

**Issue by sebi5361** [RobertBaruch/atf22v10c#1]
Dear Robert,
Thank you for your work: you made me want to give it a shot playing with GALs!
A few questions:
- What are those resistors on this [breadboard](https://www.retrobrewcomputers.org/forum/index.php?t=msg&th=108&goto=1385&#msg_1385)? Direct pin connections wouldn't work?
- Should we connect the GAL pins GND and VCC as well?
- Does your code work with an Uno rather than Due?
- Could you share the Python script to convert JDEC files into C constants?

Thanks a lot. Looking forward to receiving my GALs.

**Comment by XekriRedmane** [comment]
That's not my programmer...

**Comment by sebi5361** [comment]
Indeed, I got confused. Sorry.
Do you have additional information about your programmer and how to use it?

**Comment by XekriRedmane** [comment]
No, just what is in the sketch.
